### ISSUE TITLE
What is the snap version 1.3.1?

### ISSUE THREAD

**Issue by flexiondotorg** [akgrant43/pharo-snap#2]
Hi,

Just curious why the snap is version 1.3.1 when the version is Pharo it includes is v6.0 beta? Any chance you can align the snap version with the Pharo version so people are not confused?

**Comment by akgrant43** [comment]
Hi Martin,

On 3 May 2017 at 10:42, Martin Wimpress <notifications@github.com> wrote:

> Hi,
>
> Just curious why the snap is version 1.3.1 when the version is Pharo it
> includes is v6.0 beta? Any chance you can align the snap version with the
> Pharo version so people are not confused?
>
This is my first snap, so learning about snap packaging, Pharo packaging
and build system, getting 32 bit applications working in classic
confinement (the linux loader doesn't work properly for 32 bit apps, so
need to use patchelf), ... :-)  Using smaller numbers just allowed me to
regularly increment the number and keep notes of what I was doing.

It's always been my plan to change the version number to 6.0 prior to the
real release.

Cheers,
Alistair

**Comment by flexiondotorg** [comment]
OK, thanks for the clarification.
